name: Deploy to Satsuma Service

on:
    push:
        tags:
            - "test-*"

jobs:
    buildAndDeploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Install node
              uses: actions/setup-node@v1
              with:
                  node-version: 16
            - name: Install Yarn
              run: npm i -g yarn
            - name: Install Libs
              run: yarn --frozen-lockfile
            - name: Codegen
              run: yarn codegen:testnet
            - name: Build
              run: yarn build:testnet
            - name: Deploy to Satsuma on testnet
              run: |
                  npx graph deploy aavegotchi-core-amoy \
                    --deploy-key ${{secrets.SATSUMA_ACCESS_TOKEN}} \
                    --node https://subgraphs.alchemy.com/api/subgraphs/deploy \
                    --ipfs https://ipfs.satsuma.xyz \
                    --version-label ${GITHUB_REF#refs/*/} \
                    subgraph.testnet.yaml
              shell: bash
